#!/bin/bash
# ================================
# System Information Report Script
# ================================

# Fail quietly on missing commands to avoid ugly errors in the report
quiet() { "$@" 2>/dev/null; }

# Variables
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATE=$(date)

# OS Info
if [ -r /etc/os-release ]; then
  # shellcheck disable=SC1091
  . /etc/os-release
  OS="${NAME} ${VERSION}"
else
  OS=$(quiet lsb_release -ds || echo "Unknown Linux")
fi

# Uptime
UPTIME=$(quiet uptime -p || echo "Unknown")

# CPU Info
CPU=$(quiet lscpu | awk -F': *' '/Model name/ {print $2; exit}')
if [ -z "$CPU" ]; then
  CPU=$(quiet lshw -C processor | awk -F': ' '/product:/ {print $2; exit}')
fi
[ -z "$CPU" ] && CPU="Unknown CPU"

# RAM Info (installed/total)
RAM=$(quiet free -h | awk '/^Mem:/ {print $2; exit}')
[ -z "$RAM" ] && RAM="Unknown"

# Disk Info (make/model/size for physical disks)
DISKS=$(quiet lsblk -d -o NAME,MODEL,SIZE | awk 'NR>1 {printf "%s %s %s\n",$1,$2,$3}')
if [ -z "$DISKS" ]; then
  DISKS="None detected"
fi

# Video Card Info
VIDEO=$(quiet lshw -C display | awk -F': ' '/product:/ {print $2}' | paste -sd ", " -)
[ -z "$VIDEO" ] && VIDEO=$(quiet lspci | awk -F': ' '/VGA compatible controller/ {print $2}' | paste -sd ", " -)
[ -z "$VIDEO" ] && VIDEO="Unknown"

# Network Info
# Get interface that routes to default gateway (e.g., to 8.8.8.8) and its IP
IP_ADDR=$(quiet ip route get 8.8.8.8 | awk '/src/ {for (i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}')
GATEWAY=$(quiet ip route | awk '/^default/ {print $3; exit}')
DNS=$(awk '/^nameserver/ {print $2}' /etc/resolv.conf 2>/dev/null | paste -sd ", " -)
[ -z "$DNS" ] && DNS="Unknown"

# Users logged in
USERS=$(quiet who | awk '{print $1}' | sort -u | paste -sd "," -)
[ -z "$USERS" ] && USERS="None"

# Disk Space for local filesystems
DISK_SPACE=$(quiet df -h --local | awk 'NR>1 {print $6 ": " $4}' | paste -sd ", " -)
[ -z "$DISK_SPACE" ] && DISK_SPACE="Unknown"

# Process Count
PROC_COUNT=$(quiet ps -e --no-headers | wc -l | awk '{print $1}')
[ -z "$PROC_COUNT" ] && PROC_COUNT="Unknown"

# Load Averages
LOAD=$(quiet uptime | awk -F'load average: ' '{print $2}' | sed 's/^ *//')
[ -z "$LOAD" ] && LOAD="Unknown"

# Listening Ports
PORTS=$(quiet ss -tuln | awk '/LISTEN/ {print $5}' | awk -F':' '{print $NF}' | sort -n | uniq | paste -sd ", " -)
[ -z "$PORTS" ] && PORTS="None"

# UFW Status
UFW_STATUS=$(quiet ufw status | head -n 1)
[ -z "$UFW_STATUS" ] && UFW_STATUS="inactive or not installed"

# Output Report (blank line at start and end)
echo ""
echo "System Report for ${HOSTNAME} generated by ${USERNAME}, on ${DATE}"
echo ""
echo "System Information"
echo "------------------"
echo "OS: ${OS}"
echo "Uptime: ${UPTIME}"
echo "CPU: ${CPU}"
echo "RAM: ${RAM}"
echo "Disk(s):"
echo "${DISKS}"
echo "Video: ${VIDEO}"
echo "Host Address: ${IP_ADDR}"
echo "Gateway IP: ${GATEWAY}"
echo "DNS Server: ${DNS}"
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged In: ${USERS}"
echo "Disk Space: ${DISK_SPACE}"
echo "Process Count: ${PROC_COUNT}"
echo "Load Averages: ${LOAD}"
echo "Listening Network Ports: ${PORTS}"
echo "UFW Status: ${UFW_STATUS}"
echo ""
